# Site settings
name: Louis
email: landaship@163.com
author: Louis
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/luoyan35714/
baseurl: ""
description: 没啥说的!
meta_description: 生命在于折腾
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: landaship
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

